# Generated by Django 5.2.10 on 2026-01-09 19:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3B82F6', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='listings.listingfolder')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_folders', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'listing_folders',
                'ordering': ['order', 'name'],
                'unique_together': {('workspace', 'name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('reference_number', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('townhouse', 'Townhouse'), ('penthouse', 'Penthouse'), ('duplex', 'Duplex'), ('studio', 'Studio'), ('office', 'Office'), ('shop', 'Shop'), ('warehouse', 'Warehouse'), ('land', 'Land'), ('building', 'Building'), ('hotel_apartment', 'Hotel Apartment'), ('other', 'Other')], max_length=50)),
                ('offering_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('description_ar', models.TextField(blank=True)),
                ('location_id', models.CharField(blank=True, max_length=100)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('community', models.CharField(blank=True, max_length=200)),
                ('sub_community', models.CharField(blank=True, max_length=200)),
                ('building_name', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('price_currency', models.CharField(default='AED', max_length=3)),
                ('price_period', models.CharField(blank=True, max_length=20)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('size_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('plot_size_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('furnished', models.CharField(blank=True, max_length=20)),
                ('parking_spaces', models.IntegerField(blank=True, null=True)),
                ('floor_number', models.IntegerField(blank=True, null=True)),
                ('total_floors', models.IntegerField(blank=True, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('completion_status', models.CharField(choices=[('ready', 'Ready'), ('off_plan', 'Off Plan'), ('under_construction', 'Under Construction')], default='ready', max_length=20)),
                ('handover_date', models.DateField(blank=True, null=True)),
                ('permit_number', models.CharField(blank=True, max_length=100)),
                ('rera_number', models.CharField(blank=True, max_length=100)),
                ('broker_orn', models.CharField(blank=True, max_length=100)),
                ('agent_brn', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('sold', 'Sold'), ('rented', 'Rented'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_published_to', models.JSONField(blank=True, default=dict)),
                ('views_count', models.IntegerField(default=0)),
                ('leads_count', models.IntegerField(default=0)),
                ('favorites_count', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_until', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_listings', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='workspaces.workspace')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='listings.listingfolder')),
            ],
            options={
                'db_table': 'listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='listings.listing')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listing_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='listing_images/')),
                ('url', models.URLField(blank=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('image_type', models.CharField(choices=[('photo', 'Photo'), ('floor_plan', 'Floor Plan'), ('video_thumbnail', 'Video Thumbnail')], default='photo', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'db_table': 'listing_images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('video_type', models.CharField(choices=[('walkthrough', 'Walkthrough'), ('aerial', 'Aerial'), ('promotional', 'Promotional')], default='walkthrough', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='listings.listing')),
            ],
            options={
                'db_table': 'listing_videos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LoopConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('filter_criteria', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('interval_hours', models.IntegerField(default=24)),
                ('action', models.CharField(choices=[('refresh', 'Refresh Listing'), ('republish', 'Republish'), ('boost', 'Boost')], default='refresh', max_length=20)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loop_configs', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'loop_configs',
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['workspace', 'status'], name='listings_workspa_25e585_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['workspace', 'property_type'], name='listings_workspa_62b566_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['workspace', 'offering_type'], name='listings_workspa_4e41d6_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['reference_number'], name='listings_referen_64f3cb_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['external_id'], name='listings_externa_9c60db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listing',
            unique_together={('workspace', 'reference_number')},
        ),
    ]
