# Generated by Django 5.2.10 on 2026-01-09 19:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('secondary_phone', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('contact_type', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('tenant', 'Tenant'), ('landlord', 'Landlord'), ('investor', 'Investor'), ('agent', 'Agent'), ('other', 'Other')], default='buyer', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('linkedin_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_contacts', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_number', models.CharField(blank=True, max_length=50)),
                ('customer_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', max_length=20)),
                ('lifetime_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('vip', 'VIP')], default='active', max_length=20)),
                ('first_transaction_at', models.DateTimeField(blank=True, null=True)),
                ('last_transaction_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to='crm.contact')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(default='propertyfinder', max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('message', models.TextField(blank=True)),
                ('property_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('viewing', 'Viewing Scheduled'), ('negotiation', 'In Negotiation'), ('won', 'Won'), ('lost', 'Lost'), ('archived', 'Archived')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('budget_currency', models.CharField(default='AED', max_length=3)),
                ('preferred_locations', models.JSONField(blank=True, default=list)),
                ('property_type_preference', models.CharField(blank=True, max_length=100)),
                ('bedrooms_min', models.IntegerField(blank=True, null=True)),
                ('bedrooms_max', models.IntegerField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_contact_at', models.DateTimeField(blank=True, null=True)),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='listings.listing')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('comment_type', models.CharField(choices=[('note', 'Note'), ('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('viewing', 'Property Viewing'), ('status_change', 'Status Change')], default='note', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_comments', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.lead')),
                ('mentioned_users', models.ManyToManyField(blank=True, related_name='lead_mentions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lead_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('reminder_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lead_tasks', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.lead')),
            ],
            options={
                'db_table': 'lead_tasks',
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['workspace', 'email'], name='contacts_workspa_f2b94e_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['workspace', 'phone'], name='contacts_workspa_46b693_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['workspace', 'status'], name='leads_workspa_7a07cd_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['workspace', 'assigned_to'], name='leads_workspa_a3328e_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['workspace', 'received_at'], name='leads_workspa_aaec8a_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['external_id'], name='leads_externa_896f1f_idx'),
        ),
    ]
